### PR TITLE
fix: add rinfo to UDPHelper message event

### PR DESCRIPTION
**Pull request by Luuccc**
- Added rinfo argument to message event as it was omitted.
 - Added emit to 'message' event for consistency.
 - Including original 'data' event for projects that expect it, as
well as rinfo.
 - Renamed data arg to msg, inline with nodejs api.

### CODE REVIEW

**Comment by Luuccc** [comment]
Interesting, I sort of understand why it might be best to leave `this.emit('data', msg)` as it was originally. Even though as I understand it, the added parameter is optional.

But I'm unsure why the `Argument of type '"message"' is not assignable to parameter of type 'keyof UDPHelperEvents'.`

**Comment by Julusian** [comment]
I don't think we should emit both 'data' and 'message' events. I expect that will lead to confusion from module devs questioning what the difference is and which they should use.  
While our naming doesn't match the nodejs dgram, it is consistent with the `TCPHelper`

That typings issue is because you need to update the typescript interface here: https://github.com/bitfocus/companion-module-base/blob/cfb2a75639e663e740289aef8d5ea3f38603759a/src/helpers/udp.ts#L30
That line will need updating to include the new parameter with the correct type

**Comment by Luuccc** [comment]
I agree that might cause some confusion. 
I've removed the emit to an external 'message' event, and I've fixed the issue with the interface

**Comment by Julusian** [comment]
This is in v1.11.2

**Comment by Luuccc** [comment]
Thanks Julian, and also for the code review. I never would've guessed it's type being `dgram.RemoteInfo`, I can't find a mention of it anywhere, beyond some mentions within [net.js](https://github.com/nodejs/node/blob/64c647e3421e7756d68b4b12ee45e64d101b2956/lib/net.js#L2229) and this definition [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32744). Thanks again

**Pull request merged**
